// This file is auto-generated by src/utils/icons/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/utils/icons/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuBot, LuBrain, LuBug, LuCamera, LuCheck, LuChevronRight, LuCircleCheck, LuCloud, LuCode, LuDroplet, LuFolder, LuGem, LuGithub, LuGlobe, LuGraduationCap, LuLayoutDashboard, LuLightbulb, LuLinkedin, LuMail, LuMedal, LuMegaphone, LuMessageSquare, LuMonitorPlay, LuMousePointer, LuNewspaper, LuPackage, LuPalette, LuRocket, LuSearch, LuServer, LuShield, LuShoppingBag, LuSparkles, LuTable, LuThermometer, LuThumbsUp, LuTrees, LuTrendingUp, LuTwitter, LuType, LuUsers, LuWorkflow, LuZap } from 'react-icons/lu';
import { FaCaretRight, FaChartBar, FaPhone } from 'react-icons/fa';
import { SiFacebook } from 'react-icons/si';

export const iconMap = {
  'fa:caret-right': FaCaretRight,
  'fa:chart-bar': FaChartBar,
  'fa:phone': FaPhone,
  'lu:arrow-right': LuArrowRight,
  'lu:bot': LuBot,
  'lu:brain': LuBrain,
  'lu:bug': LuBug,
  'lu:camera': LuCamera,
  'lu:check': LuCheck,
  'lu:chevron-right': LuChevronRight,
  'lu:circle-check': LuCircleCheck,
  'lu:cloud': LuCloud,
  'lu:code': LuCode,
  'lu:droplet': LuDroplet,
  'lu:folder': LuFolder,
  'lu:gem': LuGem,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:graduation-cap': LuGraduationCap,
  'lu:layout-dashboard': LuLayoutDashboard,
  'lu:lightbulb': LuLightbulb,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:medal': LuMedal,
  'lu:megaphone': LuMegaphone,
  'lu:message-square': LuMessageSquare,
  'lu:monitor-play': LuMonitorPlay,
  'lu:mouse-pointer': LuMousePointer,
  'lu:newspaper': LuNewspaper,
  'lu:package': LuPackage,
  'lu:palette': LuPalette,
  'lu:rocket': LuRocket,
  'lu:search': LuSearch,
  'lu:server': LuServer,
  'lu:shield': LuShield,
  'lu:shopping-bag': LuShoppingBag,
  'lu:sparkles': LuSparkles,
  'lu:table': LuTable,
  'lu:thermometer': LuThermometer,
  'lu:thumbs-up': LuThumbsUp,
  'lu:trees': LuTrees,
  'lu:trending-up': LuTrendingUp,
  'lu:twitter': LuTwitter,
  'lu:type': LuType,
  'lu:users': LuUsers,
  'lu:workflow': LuWorkflow,
  'lu:zap': LuZap,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
