// This file is auto-generated by src/utils/icons/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/utils/icons/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuBadge, LuBadgeCheck, LuBot, LuBug, LuCamera, LuCheck, LuChevronRight, LuCircleCheck, LuCloud, LuCode, LuDroplet, LuFolder, LuGem, LuGithub, LuGlobe, LuLinkedin, LuMail, LuMedal, LuMegaphone, LuMessageSquare, LuMousePointer, LuPalette, LuPhoneCall, LuRefreshCw, LuRocket, LuSearch, LuServer, LuShare2, LuShield, LuSparkles, LuStar, LuSun, LuTarget, LuThermometer, LuThumbsUp, LuTrees, LuTwitter, LuType, LuUsers, LuVideo, LuWorkflow, LuZap } from 'react-icons/lu';
import { FaCaretRight, FaChartBar, FaPhone } from 'react-icons/fa';
import { SiFacebook } from 'react-icons/si';

export const iconMap = {
  'fa:caret-right': FaCaretRight,
  'fa:chart-bar': FaChartBar,
  'fa:phone': FaPhone,
  'lu:arrow-right': LuArrowRight,
  'lu:badge': LuBadge,
  'lu:badge-check': LuBadgeCheck,
  'lu:bot': LuBot,
  'lu:bug': LuBug,
  'lu:camera': LuCamera,
  'lu:check': LuCheck,
  'lu:chevron-right': LuChevronRight,
  'lu:circle-check': LuCircleCheck,
  'lu:cloud': LuCloud,
  'lu:code': LuCode,
  'lu:droplet': LuDroplet,
  'lu:folder': LuFolder,
  'lu:gem': LuGem,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:medal': LuMedal,
  'lu:megaphone': LuMegaphone,
  'lu:message-square': LuMessageSquare,
  'lu:mouse-pointer': LuMousePointer,
  'lu:palette': LuPalette,
  'lu:phone-call': LuPhoneCall,
  'lu:refresh-cw': LuRefreshCw,
  'lu:rocket': LuRocket,
  'lu:search': LuSearch,
  'lu:server': LuServer,
  'lu:share-2': LuShare2,
  'lu:shield': LuShield,
  'lu:sparkles': LuSparkles,
  'lu:star': LuStar,
  'lu:sun': LuSun,
  'lu:target': LuTarget,
  'lu:thermometer': LuThermometer,
  'lu:thumbs-up': LuThumbsUp,
  'lu:trees': LuTrees,
  'lu:twitter': LuTwitter,
  'lu:type': LuType,
  'lu:users': LuUsers,
  'lu:video': LuVideo,
  'lu:workflow': LuWorkflow,
  'lu:zap': LuZap,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
